src/SiteWithPostgres.Web/Models/Shared/ConfirmationViewModel.cs
namespace SiteWithPostgres.Web.Models.Shared
{
    public class ConfirmationViewModel
    {
        public string PageTitle { get; set; }
        public string ConfirmationMessage { get; set; }
    }
}

src/SiteWithPostgres.Web/Models/Shared/NewsListViewModel.cs
using System.Collections.Generic;
using SiteWithPostgres.Entities;

namespace SiteWithPostgres.Web.Models.Shared
{
    public class NewsListViewModel
    {
        public IEnumerable<News> Newses { get; set; }
        public IEnumerable<Testimonial> Testimonials { get; set; }
    }
}

src/SiteWithPostgres.Web/Models/Shared/PageViewModel.cs
using SiteWithPostgres.Entities;

namespace SiteWithPostgres.Web.Models.Shared
{
    public class PageViewModel
    {
        public Page Page { get; set; }
        public Image Image { get; set; }
    }
}

src/SiteWithPostgres.Web/Models/Shared/ResourceViewModel.cs
using SiteWithPostgres.Entities;

namespace SiteWithPostgres.Web.Models.Shared
{
    public class ResourceViewModel
    {
        public string Name { get; set; }
        public string Value { get; set; }

        public static ResourceViewModel Create(Resource resource)
        {
            return new ResourceViewModel()
            {
                Value = resource.Value,
                Name = resource.Name
            };
        }
    }
}

src/SiteWithPostgres.Web/Areas/Api/Controllers/UsersController.cs
using SiteWithPostgres.Core.Email;
using SiteWithPostgres.Core.Enums;
using SiteWithPostgres.Core.Formate;
using SiteWithPostgres.Core.Security;
using SiteWithPostgres.Core.Service;
using SiteWithPostgres.Entities;
using SiteWithPostgres.Services;
using SiteWithPostgres.Services.Identity;
using SiteWithPostgres.Web.Areas.Api.Models.Users;
using SiteWithPostgres.Web.Areas.User.Models.Account;
using SiteWithPostgres.Web.Core.Services;
using SiteWithPostgres.Web.Extensions;
using SiteWithPostgres.Web.Models.Account;
using SiteWithPostgres.Web.Resources;
using OrangeJetpack.Localization;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;
using SiteWithPostgres.Web.Areas.Api.Filters;

namespace SiteWithPostgres.Web.Areas.Api.Controllers
{
    [LanguageFilter]
    [RoutePrefix("api/users")]
    public class UsersController : ApplicationApiController
    {
        private readonly IMessageService _messageService;
        private readonly IAuthService _authService;
        private readonly UserService _userService;
        private readonly EmailTemplateService _emailTemplateService;

        public UsersController(IAppServices appServices) : base(appServices)
        {
            _messageService = appServices.MessageService;
            _authService = appServices.AuthService;
            _userService = new UserService(appServices.DataContextFactory);
            _emailTemplateService = new EmailTemplateService(DataContextFactory);
        }

        [Authorize]
        [HttpGet, Route("{id}", Name = "GetUser")]
        public async Task<IHttpActionResult> GetUser(string id)
        {
            var user = await _userService.GetUserById(id);
            if (user == null)
            {
                return NotFound();
            }

            return Ok(new
            {
                user.Id,
                user.Email,
                user.FirstName,
                user.LastName,
                user.PhoneCountryCode,
                user.PhoneLocalNumber,
                user.CreatedUtc
            });
        }

        [Route(""), HttpPost]
        public async Task<IHttpActionResult> Register(RegisterViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return ModelStateError(ModelState);
            }

            var user = new Entities.User
            {
                UserName = model.Email,
                Email = model.Email,
                FirstName = model.FirstName,
                LastName = model.LastName
            };

            var result = await AuthService.CreateUser(user, model.Password);
            if (!result.Succeeded)
            {
                return IdentityResultError(result);
            }

            await SendNewUserWelcomeEmail(user);

            return CreatedAtRoute("GetUser", new { id = user.Id }, new
            {
                user.Id,
                user.Email,
                user.FirstName,
                user.LastName,
                user.PhoneCountryCode,
                user.PhoneLocalNumber,
                user.CreatedUtc
            });
        }

        [Route("{id}/password-reset"), HttpPost]
        public async Task<IHttpActionResult> RequestPasswordReset(NeedPasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return ModelStateError(ModelState);
            }

            await SendPasswordResetNotification(model.Email);
            return Ok("Password has been sent");
        }

        [Authorize, HttpPut, Route("{id}")]
        public async Task<IHttpActionResult> UpdateUser(string id, UserModel model)
        {
            var user = await _userService.GetUserById(id);
            if (user == null)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return ModelStateError(ModelState);
            }

            var originalEmail = user.Email;
            user.FirstName = model.FirstName;
            user.LastName = model.LastName;
            user.Email = model.Email;

            await _userService.UpdateUser(user);

            if (originalEmail != user.Email)
            {
                await SendEmailChangedEmail(user, originalEmail);
            }

            return Ok();
        }

        [Authorize]
        [Route("{id}/password"), HttpPut]
        public async Task<IHttpActionResult> ChangePassword(string id, ChangePasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return ModelStateError(ModelState);
            }

            var result = await _authService.ChangePassword(User.Identity, model.CurrentPassword, model.NewPassword);
            if (!result.Succeeded)
            {
                return IdentityResultError(result);
            }

            await SendPasswordChangedEmail();

            return Ok();
        }

        private async Task SendNewUserWelcomeEmail(Entities.User user)
        {
            var template = await _emailTemplateService.GetByTemplateType(EmailTemplateType.AccountRegistration, LanguageCode);

            var email = new Email
            {
                ToAddress = user.Email,
                Subject = StringFormatter.ObjectFormat(template.Subject, new { AppSettings.SiteTitle }),
                Message = StringFormatter.ObjectFormat(template.Message, new { AppSettings.SiteTitle, user.FirstName })
            };

            try
            {
                await _messageService.Send(email.WithTemplate());
            }
            catch (Exception ex)
            {
                ErrorLogger.Log(ex);
            }
        }

        private async Task SendEmailChangedEmail(Entities.User user, string originalEmail)
        {
            var template = await _emailTemplateService.GetByTemplateType(EmailTemplateType.EmailChanged);
            var email = new Email
            {
                ToAddress = originalEmail,
                Subject = template.Localize(LanguageCode, i => i.Subject).Subject,
                Message = StringFormatter.ObjectFormat(template.Localize(LanguageCode, i => i.Message).Message, new { user.FirstName, AppSettings.SiteTitle })
            };

            try
            {
                await _messageService.Send(email.WithTemplate());
            }
            catch (Exception ex)
            {
                ErrorLogger.Log(ex);
            }
        }

        private async Task SendPasswordResetNotification(string emailAddress)
        {
            EmailTemplate template;
            var email = new Email
            {
                ToAddress = emailAddress,
                Subject = Global.ResetPassword
            };

            var user = await _userService.GetUserByEmail(emailAddress);
            if (user == null)
            {
                template = await _emailTemplateService.GetByTemplateType(EmailTemplateType.NoAccount, LanguageCode);
                email.Subject = template.Subject;
                email.Message = StringFormatter.ObjectFormat(template.Message, new { emailAddress });
            }
            else
            {
                var resetUrl = GetPasswordResetUrl(user.Email);

                template = await _emailTemplateService.GetByTemplateType(EmailTemplateType.PasswordReset, LanguageCode);
                email.Subject = template.Subject;
                email.Message = StringFormatter.ObjectFormat(template.Message, new
                {
                    EmailAddress = user.FirstName,
                    ResetPasswordUrl = resetUrl
                });
            }

            try
            {
                await _messageService.Send(email.WithTemplate());
            }
            catch (Exception ex)
            {
                ErrorLogger.Log(ex);
            }
        }

        private string GetPasswordResetUrl(string email)
        {
            var baseUrl = GetBaseUrl("resetpassword");

            return PasswordUtilities.GenerateResetPasswordUrl(baseUrl, email);
        }

        private string GetBaseUrl(string action)
        {
            var baseUri = new Uri(Request.RequestUri.AbsoluteUri.Replace(Request.RequestUri.PathAndQuery, ""));

            var resourceRelative = "~/en/account/" + action;
            var resourceFullPath = new Uri(baseUri, VirtualPathUtility.ToAbsolute(resourceRelative));

            return resourceFullPath.AbsoluteUri;
        }

        private async Task SendPasswordChangedEmail()
        {
            var user = await _authService.CurrentUser();
            var template = await _emailTemplateService.GetByTemplateType(EmailTemplateType.PasswordChanged, LanguageCode);
            var email = new Email
            {
                ToAddress = user.Email,
                Subject = template.Subject,
                Message = StringFormatter.ObjectFormat(template.Message, new { user.FirstName, AppSettings.SiteTitle })
            };

            try
            {
                await _messageService.Send(email.WithTemplate());
            }
            catch (Exception ex)
            {
                ErrorLogger.Log(ex);
            }
        }

        [Route("get-all"), HttpGet]
        [AllowAnonymous]
        public async Task<IHttpActionResult> GetAll()
        {
            var users = await _userService.GetUsers();
            return Ok(users.Select(i => new
            {
                i.Id,
                Name = NameFormatter.Formate(i.FirstName, i.LastName),
                i.Email,
                i.PhoneNumber,
                PhotoPath = $"{AppSettings.Url}/SystemDir/Users/{i.Image}"  
            }).ToList());
        }
    }
}

src/SiteWithPostgres.Web/Areas/admin/Controllers/PagesController.cs
using System;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using OrangeJetpack.Localization;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using SiteWithPostgres.Core.UI;
using SiteWithPostgres.Entities;
using SiteWithPostgres.Services;
using SiteWithPostgres.Web.Areas.Admin.Models.Pages;
using SiteWithPostgres.Web.Core.Attributes;
using SiteWithPostgres.Web.Core.Services;

namespace SiteWithPostgres.Web.Areas.Admin.Controllers
{
    [LanguageRoutePrefix("admin", "pages")]
    public class PagesController : AdminBaseController
    {
        private readonly PageService _pageService;

        public PagesController(IAppServices appServices) : base(appServices)
        {
            _pageService = new PageService(DataContextFactory);
        }

        [Route("")]
        public ActionResult Index()
        {
            var model = new IndexViewModel();
            return View(model);
        }

        [Route("get-data")]
        public async Task<JsonResult> GetData([DataSourceRequest] DataSourceRequest request, string search)
        {
            var data = await _pageService.GetAll();
            data = data.Localize(LanguageCode, i => i.Title).ToList();
            return Json(data.ToDataSourceResult(request));
        }

        [Route("add")]
        public ActionResult Add()
        {
            var model = new AddEditViewModel()
            {
                Page = new Page()
                {
                    Title = LocalizedContent.Init(),
                    Content = LocalizedContent.Init(),
                    Preview = LocalizedContent.Init()
                }
            };
            return View(model);
        }

        [Route("add")]
        [HttpPost, ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public async Task<ActionResult> Add(AddEditViewModel model, LocalizedContent[] title)
        {
            if (ModelState.ContainsKey("Page.Title"))
                ModelState["Page.Title"].Errors.Clear();
            if (!ModelState.IsValid)
            {
                model.Page.Title = LocalizedContent.Init();
                return View(model);
            }

            model.Page.Title = title.Serialize();
            model.Page.Content = LocalizedContent.Init();
            model.Page.Preview = LocalizedContent.Init();
            await _pageService.Add(model.Page);
            SetStatusMessage("Page has been added successfully.");
            return RedirectToAction("Index");

        }


        [Route("{id:int}/edit")]
        [ValidateInput(false)]
        public async Task<ActionResult> Edit(int id)
        {

            var page = await _pageService.GetById(id);
            if (page == null)
            {
                return HttpNotFound();
            }

            var model = new AddEditViewModel()
            {
                Page = page
            };
            return View(model);
        }

        [Route("{id:int}/edit")]
        [HttpPost, ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public async Task<ActionResult> Edit(int id, AddEditViewModel model, LocalizedContent[] title, LocalizedContent[] content, LocalizedContent[] preview)
        {
            try
            {
                model.Page.Title = title.Serialize();
                model.Page.Content = content.Serialize();
                model.Page.Preview = preview.Serialize();
                await _pageService.Edit(model.Page);
                SetStatusMessage("Page has been saved successfully.");
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                SetStatusMessage("Sorry, Unable to update page please try agine.", StatusMessageType.Error);
                return RedirectToAction("Edit", new {id = id});
            }
            

        }

        [Route("{id:int}/delete")]
        public async Task<ActionResult> Delete(int id)
        {

            var page = await _pageService.GetById(id);
            if (page == null)
            {
                return HttpNotFound();
            }

            return Confirmation("Delete Page", "Are you sure want to delete this page?");
        }

        [Route("{id:int}/delete")]
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, FormCollection model)
        {
            var page = await _pageService.GetById(id);
            if (page == null)
            {
                return HttpNotFound();
            }

            await _pageService.Remove(page);
            SetStatusMessage("Page has been removed successfully.");
            return RedirectToAction("Index");

        }


    }
}

src/SiteWithPostgres.Web/Areas/admin/Views/Shared/_Layout.cshtml
@using Kendo.Mvc.UI

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section styles {
    @Styles.Render("~/css/admin")
    @RenderSection("styles", false)
}



<div class="container" style="padding-bottom: 50px;">
    @RenderBody()
</div>

@section scripts {
    <script src="//cdn.ckeditor.com/4.7.2/full/ckeditor.js"></script>
    <script src="~/scripts/kendo.web.min.js"></script>
    <script src="~/Scripts/kendo.aspnetmvc.min.js"></script>
    
    @Html.Kendo().DeferredScripts()
    @RenderSection("scripts", false)
}

src/SiteWithPostgres.Web/Areas/admin/Views/Shared/_LeftMenu.cshtml
<div 
    id="m_ver_menu" 
    class="m-aside-menu  m-aside-menu--skin-dark m-aside-menu--submenu-skin-dark " 
    data-menu-vertical="true"
    data-menu-scrollable="false" data-menu-dropdown-timeout="500"  
>
    <ul class="m-menu__nav  m-menu__nav--dropdown-submenu-arrow ">
        <li class="m-menu__item  m-menu__item--active" aria-haspopup="true">
            <a href="@Url.Action("Index", "Home", new {Area="Admin", LanguageCode})" class="m-menu__link ">
                <i class="m-menu__link-icon flaticon-line-graph"></i>
                <span class="m-menu__link-title">
                    <span class="m-menu__link-wrap">
                        <span class="m-menu__link-text">
                            Dashboard
                        </span>
                        <span class="m-menu__link-badge">
                            <span class="m-badge m-badge--danger">
                                2
                            </span>
                        </span>
                    </span>
                </span>
            </a>
        </li>
        <li class="m-menu__section">
            <h4 class="m-menu__section-text">
                Components
            </h4>
            <i class="m-menu__section-icon flaticon-more-v3"></i>
        </li>
        <li class="m-menu__item  m-menu__item--submenu" aria-haspopup="true" data-menu-submenu-toggle="hover">
            <a href="#" class="m-menu__link m-menu__toggle">
                <i class="m-menu__link-icon fa fa-users"></i>
                <span class="m-menu__link-text">
                    Users
                </span>
                <i class="m-menu__ver-arrow la la-angle-right"></i>
            </a>
            <div class="m-menu__submenu ">
                <span class="m-menu__arrow"></span>
                <ul class="m-menu__subnav">
                    <li class="m-menu__item  m-menu__item--parent" aria-haspopup="true">
                        <span class="m-menu__link">
                            <span class="m-menu__link-text">
                                Users
                            </span>
                        </span>
                    </li>
                    <li class="m-menu__item " aria-haspopup="true">
                        <a href="@Url.Action("Index", "Users", new {Area="Admin", LanguageCode})" class="m-menu__link ">
                            <i class="m-menu__link-bullet m-menu__link-bullet--dot">
                                <span></span>
                            </i>
                            <span class="m-menu__link-text">
                                List Of Users
                            </span>
                        </a>
                    </li>
                    
                </ul>
            </div>
        </li>
        <li class="m-menu__item  m-menu__item--submenu" aria-haspopup="true" data-menu-submenu-toggle="hover">
            <a href="#" class="m-menu__link m-menu__toggle">
                <i class="m-menu__link-icon flaticon-layers"></i>
                <span class="m-menu__link-text">
                    Pages
                </span>
                <i class="m-menu__ver-arrow la la-angle-right"></i>
            </a>
            <div class="m-menu__submenu ">
                <span class="m-menu__arrow"></span>
                <ul class="m-menu__subnav">
                    <li class="m-menu__item  m-menu__item--parent" aria-haspopup="true">
                        <span class="m-menu__link">
                            <span class="m-menu__link-text">
                                Pages
                            </span>
                        </span>
                    </li>
                    <li class="m-menu__item " aria-haspopup="true">
                        <a href="@Url.Action("Index", "Pages", new {Area="Admin", LanguageCode})" class="m-menu__link ">
                            <i class="m-menu__link-bullet m-menu__link-bullet--dot">
                                <span></span>
                            </i>
                            <span class="m-menu__link-text">
                                List Of Pages
                            </span>
                        </a>
                    </li>
                    <li class="m-menu__item " aria-haspopup="true">
                        <a href="@Url.Action("Add", "Pages", new {Area="Admin", LanguageCode})" class="m-menu__link ">
                            <i class="m-menu__link-bullet m-menu__link-bullet--dot">
                                <span></span>
                            </i>
                            <span class="m-menu__link-text">
                                Add New Page
                            </span>
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="m-menu__item  m-menu__item--submenu" aria-haspopup="true" data-menu-submenu-toggle="hover">
            <a href="#" class="m-menu__link m-menu__toggle">
                <i class="m-menu__link-icon fa fa-line-chart"></i>
                <span class="m-menu__link-text">
                    Services
                </span>
                <i class="m-menu__ver-arrow la la-angle-right"></i>
            </a>
            <div class="m-menu__submenu ">
                <span class="m-menu__arrow"></span>
                <ul class="m-menu__subnav">
                    <li class="m-menu__item  m-menu__item--parent" aria-haspopup="true">
                        <span class="m-menu__link">
                            <span class="m-menu__link-text">
                                Services
                            </span>
                        </span>
                    </li>
                    <li class="m-menu__item " aria-haspopup="true">
                        <a href="@Url.Action("Index", "Services", new {Area="Admin", LanguageCode})" class="m-menu__link ">
                            <i class="m-menu__link-bullet m-menu__link-bullet--dot">
                                <span></span>
                            </i>
                            <span class="m-menu__link-text">
                                List Of All Services
                            </span>
                        </a>
                    </li>
                    <li class="m-menu__item " aria-haspopup="true">
                        <a href="@Url.Action("Add", "Services", new {Area="Admin", LanguageCode})" class="m-menu__link ">
                            <i class="m-menu__link-bullet m-menu__link-bullet--dot">
                                <span></span>
                            </i>
                            <span class="m-menu__link-text">
                                Add New Service
                            </span>
                        </a>
                    </li>
                </ul>
            </div>
        </li>
    </ul>
</div>

src/SiteWithPostgres.Web/Areas/admin/Views/Shared/_UserProfile.cshtml
@using Microsoft.AspNet.Identity
@using SiteWithPostgres.Web.Extensions
<li class="m-nav__item m-topbar__user-profile m-topbar__user-profile--img  m-dropdown m-dropdown--medium m-dropdown--arrow m-dropdown--header-bg-fill m-dropdown--align-right m-dropdown--mobile-full-width m-dropdown--skin-light" data-dropdown-toggle="click">
    <a href="#" class="m-nav__link m-dropdown__toggle">
        <span class="m-topbar__userpic">
            <img src="~/Content/metroc/app/media/img/users/user4.jpg" class="m--img-rounded m--marginless m--img-centered" alt="" />
        </span>
        <span class="m-topbar__username m--hide">
            @User.Identity.GetDisplayName()
        </span>
    </a>
    <div class="m-dropdown__wrapper">
        <span class="m-dropdown__arrow m-dropdown__arrow--right m-dropdown__arrow--adjust"></span>
        <div class="m-dropdown__inner">
            <div class="m-dropdown__header m--align-center" style="background: url(assets/app/media/img/misc/user_profile_bg.jpg); background-size: cover;">
                <div class="m-card-user m-card-user--skin-dark">
                    <div class="m-card-user__pic">
                        <img src="~/Content/metroc/app/media/img/users/user4.jpg" class="m--img-rounded m--marginless" alt="" />
                    </div>
                    <div class="m-card-user__details">
                        <span class="m-card-user__name m--font-weight-500">
                            @User.Identity.GetDisplayName()
                        </span>
                        <a href="" class="m-card-user__email m--font-weight-300 m-link">
                            @User.Identity.GetUserName()
                        </a>
                    </div>
                </div>
            </div>
            <div class="m-dropdown__body">
                <div class="m-dropdown__content">
                    <ul class="m-nav m-nav--skin-light">
                        <li class="m-nav__section m--hide">
                            <span class="m-nav__section-text">
                                Section
                            </span>
                        </li>
                        <li class="m-nav__item">
                            <a href="@Url.Action("MyAccount", "Account", new {Area="User", LanguageCode})" class="m-nav__link">
                                <i class="m-nav__link-icon flaticon-profile-1"></i>
                                <span class="m-nav__link-title">
                                    <span class="m-nav__link-wrap">
                                        <span class="m-nav__link-text">
                                            My Profile
                                        </span>
                                        
                                    </span>
                                </span>
                            </a>
                        </li>
                        
                        <li class="m-nav__item">
                            <a href="header/profile.html" class="m-nav__link">
                                <i class="m-nav__link-icon flaticon-chat-1"></i>
                                <span class="m-nav__link-title">
                                    <span class="m-nav__link-wrap">
                                        <span class="m-nav__link-text">
                                            Messages
                                        </span>
                                        <span class="m-nav__link-badge">
                                            <span class="m-badge m-badge--success">
                                                2
                                            </span>
                                        </span>
                                    </span>
                                </span>
                            </a>
                        </li>
                        
                        <li class="m-nav__item">
                            <a href="@Url.Action("LogOut", "Account", new {Area="", LanguageCode})" class="btn m-btn--pill    btn-secondary m-btn m-btn--custom m-btn--label-brand m-btn--bolder">
                                Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</li>